kind: Service
apiVersion: v1
metadata:
  name: lc-master
  namespace: wordlettercount
spec:
  selector:
    app: lc-master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: lc-master
  namespace: wordlettercount
  labels:
    app: lc-master
spec:
  serviceAccountName: ksa
  containers:
    - name: lc-master
      image: matchy233/master-lettercount:v0.0.3
      ports:
        - containerPort: 8080
          name: mapper
      env:
        - name: MAPPER_HOST
          value: "lc-mapper"
        - name: REDUCER_HOST
          value: "reducers"
        - name: MAPPER_PORT
          value: "8080"
        - name: REDUCER_PORT
          value: "8080"
      args: ["-input=inputs/input1", "-output=outputs/lcoutput1"]
  restartPolicy: Never