kind: Service
apiVersion: v1
metadata:
  name: master
  namespace: wordlettercount
spec:
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: master
  namespace: wordlettercount
  labels:
    app: master
spec:
  serviceAccountName: ksa
  containers:
    - name: master
      image: matchy233/master:v0.0.4
      ports:
        - containerPort: 8080
          name: master
      env:
        - name: MAPPER_HOST
          value: "mappers"
        - name: REDUCER_HOST
          value: "reducers"
        - name: MAPPER_PORT
          value: "8080"
        - name: REDUCER_PORT
          value: "8080"
      args: [ "-input=inputs/input1", "-output=outputs/output2" ]
  restartPolicy: Never