apiVersion: v1
kind: Service
metadata:
  name: mappers
  namespace: wordlettercount
  labels:
    app: mappers
spec:
  ports:
    - port: 8080
      name: mappers
  clusterIP: None
  selector:
    app: mappers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mappers
  namespace: wordlettercount
spec:
  serviceName: "mappers"
  replicas: 0
  selector:
    matchLabels:
      app: mappers
  template:
    metadata:
      labels:
        app: mappers
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: key
                    operator: NotIn
                    values:
                      - node1
                      - node2
      containers:
        - name: mappers
          image: matchy233/mapper:v0.0.1
          ports:
            - containerPort: 8080
              name: mappers